on: push
name: npm build, lint, test and publish
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install
      #- run: npm test
      #- name: npm lint
      #  uses: actions/npm@master
      #  with:
      #    args: run lint
      - name: docker build and push
        if: github.ref == 'master'
        uses: jerray/publish-docker-action@v1.0.3
        with:
          registry: docker.pkg.github.com
          repository: evryfs/psd2-developer/psd2-developer
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          auto_tag: true
